# Generated by Django 4.2.3 on 2024-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlens', '0003_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
