# Generated by Django 4.2.3 on 2024-03-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlens', '0004_intake_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
